import { language } from '../config'

export const resources = {
  'zh-CN': {
    appName: '喵视器',

    configure: '配置',

    alignment: '对齐方式',
    left: '向左对齐',
    center: '中间对齐',
    right: '向右对齐',

    style: '风格',
    dark: '暗黑',
    light: '明亮',

    updateSpeed: '更新速度',
    high: '高',
    normal: '正常',
    low: '低',

    dragPosition: '拖拽位置',
    open: '打开',
    close: '关闭',
    defaultLocation: '默认位置',
    enableMonitorDragging: '开启监视器拖拽',
    disableMonitorDragging: '禁用监视器拖拽',

    autoStart: '自启动',

    languages: '多语言',
    enUS: 'English - 英文',
    zhCN: '中文(简体) - 中文(简体)',
    zhTW: '中文(繁體) - 中文(繁体)',

    quit: '退出',

    about: '关于',
    version: '版本',
    github: 'Github',

    fontSize: "字体大小",

    weather0: "晴",
    weather1: "晴",
    weather2: "多云",
    weather3: "阴",
    weather45: "雾",
    weather48: "雾霾",
    weather51: "小雨",
    weather53: "中雨",
    weather55: "大雨",
    weather56: "小冻雨",
    weather57: "大冻雨",
    weather61: "小雨",
    weather63: "中雨",
    weather65: "大雨",
    weather66: "小冻雨",
    weather67: "大冻雨",
    weather71: "小雪",
    weather73: "中雪",
    weather75: "大雪",
    weather77: "霰",
    weather80: "小阵雨",
    weather81: "中阵雨",
    weather82: "大阵雨",
    weather85: "小阵雪",
    weather86: "大阵雪",
    weather95: "雷阵雨",
    weather96: "小冰雹",
    weather99: "大冰雹",

    windDirection1: "北风",
    windDirection2: "东北风",
    windDirection3: "东风",
    windDirection4: "东南风",
    windDirection5: "南风",
    windDirection6: "西南风",
    windDirection7: "西风",
    windDirection8: "西北风",
    windDirection9: "旋转风",
    windDirection10: "无持续风向",
  },
  'zh-TW': {
    appName: '喵視器',

    configure: '配置',

    alignment: '對齊方式',
    left: '向左對齊',
    center: '中間對齊',
    right: '向右對齊',

    style: '風格',
    dark: '暗黑',
    light: '明亮',

    updateSpeed: '更新速度',
    high: '高',
    normal: '正常',
    low: '低',

    dragPosition: '拖拽位置',
    open: '打開',
    close: '關閉',
    defaultLocation: '默認位置',
    enableMonitorDragging: '開啟監視器拖拽',
    disableMonitorDragging: '禁用監視器拖拽',

    autoStart: '自啟動',

    languages: '多語言',
    enUS: 'English - 英文',
    zhCN: '中文(簡體) - 中文(簡體)',
    zhTW: '中文(繁體) - 中文(繁體)',

    quit: '退出',

    about: '關於',
    version: '版本',
    github: 'Github',

    fontSize: "字體大小",

    weather0: "晴",
    weather1: "晴",
    weather2: "多雲",
    weather3: "陰",
    weather45: "霧",
    weather48: "霧霾",
    weather51: "小雨",
    weather53: "中雨",
    weather55: "大雨",
    weather56: "小凍雨",
    weather57: "大凍雨",
    weather61: "小雨",
    weather63: "中雨",
    weather65: "大雨",
    weather66: "小凍雨",
    weather67: "大凍雨",
    weather71: "小雪",
    weather73: "中雪",
    weather75: "大雪",
    weather77: "霰",
    weather80: "小陣雨",
    weather81: "中陣雨",
    weather82: "大陣雨",
    weather85: "小陣雪",
    weather86: "大陣雪",
    weather95: "雷陣雨",
    weather96: "小冰雹",
    weather99: "大冰雹",

    windDirection1: "北風",
    windDirection2: "東北風",
    windDirection3: "東風",
    windDirection4: "東南風",
    windDirection5: "南風",
    windDirection6: "西南風",
    windDirection7: "西風",
    windDirection8: "西北風",
    windDirection9: "旋轉風",
    windDirection10: "無持續風向",
  },
  'en-US': {
    appName: 'Meow Monitor',

    configure: 'Configure',

    alignment: 'Alignment',
    left: 'Left',
    center: 'Center',
    right: 'Right',

    style: 'Style',
    dark: 'Dark',
    light: 'Light',

    updateSpeed: 'Update speed',
    high: 'High',
    normal: 'Normal',
    low: 'Low',

    dragPosition: 'Drag position',
    open: 'Open',
    close: 'Close',
    defaultLocation: 'Default location',
    enableMonitorDragging: 'Enable monitor dragging',
    disableMonitorDragging: 'Disable monitor dragging',

    autoStart: 'Auto start',

    languages: 'Languages',
    enUS: 'English - English',
    zhCN: '中文(简体) - Chinese(Simplified)',
    zhTW: '中文(繁體) - Chinese(Traditional)',

    quit: 'Quit',

    about: 'About',
    version: 'Version',
    github: 'Github',

    fontSize: "Font size",


    weather0: "Sunny",
    weather1: "Sunny",
    weather2: "Partly cloudy",
    weather3: "Overcast",
    weather45: "Fog",
    weather48: "Haze",
    weather51: "Light rain",
    weather53: "Moderate rain",
    weather55: "Heavy rain",
    weather56: "Light freezing rain",
    weather57: "Heavy freezing rain",
    weather61: "Light rain",
    weather63: "Moderate rain",
    weather65: "Heavy rain",
    weather66: "Light freezing rain",
    weather67: "Heavy freezing rain",
    weather71: "Light snow",
    weather73: "Moderate snow",
    weather75: "Heavy snow",
    weather77: "Grain snow",
    weather80: "Light showers",
    weather81: "Moderate showers",
    weather82: "Heavy showers",
    weather85: "Light snow showers",
    weather86: "Heavy snow showers",
    weather95: "Thunderstorm",
    weather96: "Small hail",
    weather99: "Large hail",

    windDirection1: "North wind",
    windDirection2: "Northeast wind",
    windDirection3: "East wind",
    windDirection4: "Southeast wind",
    windDirection5: "South wind",
    windDirection6: "Southwest wind",
    windDirection7: "West wind",
    windDirection8: "Northwest wind",
    windDirection9: "Rotating wind",
    windDirection10: "No sustained wind direction",
  },
}

export const t = (parameter: keyof typeof resources['en-US']): string => {
  return resources?.[language]?.[parameter] || parameter
}